### ISSUE TITLE
Error when run vlog_read_script_sample.py

### ISSUE THREAD

**Issue by huanmx** [Vchitect/Vlogger#15]
Hello! 
Thanks for your great work!
I have run vlog_write_script.py and generated scripts and ref_imgs of teddy_travel with gpt-3.5. When I run vlog_read_script_sample.py, this error occurs.
Traceback (most recent call last):
  File "sample_scripts/vlog_read_script_sample.py", line 306, in <module>
    main(omega_conf)
  File "sample_scripts/vlog_read_script_sample.py", line 189, in main
    pil_image = Image.open(args.reference_image_path[reference_lists[i][0] - 1])
  File "/root/miniconda3/envs/vlogger/lib/python3.8/site-packages/omegaconf/listconfig.py", line 218, in __getitem__
    self._format_and_raise(key=index, value=None, cause=e)
  File "/root/miniconda3/envs/vlogger/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/root/miniconda3/envs/vlogger/lib/python3.8/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/root/miniconda3/envs/vlogger/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/root/miniconda3/envs/vlogger/lib/python3.8/site-packages/omegaconf/listconfig.py", line 215, in __getitem__
    key=index, value=self.__dict__["_content"][index]
omegaconf.errors.ConfigIndexError: list index out of range
    full_key: reference_image_path[1]
    object_type=list

**Comment by zhuangshaobin** [comment]
It seems that there are some errors in the reference_lists. 

It is recommended to check the contents in: 
results/vlog/$your_vlog/script/protagonist_place_reference.txt 
to check whether the indexes of the protagonists referenced by all fragments are less than or equal to the number of protagonists.

Due to GPT version changes and black box calling methods, there is a small probability that scripts with error messages will be generated.

It would also be a simple and effective way to regenerate the script.

**Comment by huanmx** [comment]
Thanks for your reply.
The contents in generated protagonists are as follows:
[
        {
            "video segment id": 1,
            "character/place id": [1]
        },
        {
            "video segment id": 2,
            "character/place id": [1]
        },
        {
            "video segment id": 3,
            "character/place id": [0]
        },
        {
            "video segment id": 4,
            "character/place id": [2]
        },
        {
            "video segment id": 5,
            "character/place id": [3]
        },
        {
            "video segment id": 6,
            "character/place id": [3]
        },
        {
            "video segment id": 7,
            "character/place id": [0]
        },
        {
            "video segment id": 8,
            "character/place id": [0]
        }
]
I have tried to regenerate the script and the result is similar to the above. So is this problem mainly caused by the poor generation result of GPT-3.5.
