### ISSUE TITLE
I cannot install bark_ssg==1.3.4, because of hoedown

### ISSUE THREAD

**Issue by waternight1029** [Vchitect/Vlogger#6]
How can I do with it?
When running "/vlog_read_script_sample.py"
hoedown.c
      hoedownpy/hoedown.c(4501): error C2105: “++”需要左值
      hoedownpy/hoedown.c(4503): error C2105: “--”需要左值
      hoedownpy/hoedown.c(4762): error C2105: “++”需要左值
      hoedownpy/hoedown.c(4764): error C2105: “--”需要左值
      hoedownpy/hoedown.c(5164): error C2039: "tp_print": 不是 "_typeobject" 的成员
      C:\Users\xxx\anaconda3\envs\vlogger\include\cpython/object.h(191): note: 参见“_typeobject”的声明
      hoedownpy/hoedown.c(5172): error C2039: "tp_print": 不是 "_typeobject" 的成员
      C:\Users\xxx\anaconda3\envs\vlogger\include\cpython/object.h(191): note: 参见“_typeobject”的声明
      hoedownpy/hoedown.c(5181): error C2039: "tp_print": 不是 "_typeobject" 的成员
      C:\Users\xxx\anaconda3\envs\vlogger\include\cpython/object.h(191): note: 参见“_typeobject”的声明
      hoedownpy/hoedown.c(5190): error C2039: "tp_print": 不是 "_typeobject" 的成员
      C:\Users\xxx\anaconda3\envs\vlogger\include\cpython/object.h(191): note: 参见“_typeobject”的声明
      hoedownpy/hoedown.c(5198): error C2039: "tp_print": 不是 "_typeobject" 的成员
      C:\Users\xxx\anaconda3\envs\vlogger\include\cpython/object.h(191): note: 参见“_typeobject”的声明
      hoedownpy/hoedown.c(5808): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      hoedownpy/hoedown.c(5824): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      hoedownpy/hoedown.c(6213): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hoedown
  Running setup.py clean for hoedown
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: option --all not recognized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for hoedown
Failed to build hoedown
ERROR: Could not build wheels for hoedown, which is required to install pyproject.toml-based projects

**Comment by PolarisLight** [comment]
Same problem, hoping to get a reply soon.

**Comment by zhuangshaobin** [comment]
It appears that you are encountering build errors while trying to install the `hoedown` Python package. The error messages suggest issues with C code in the `hoedown` package, possibly related to compatibility with the Visual Studio compiler.

Here are a few steps you can try to resolve this issue:

1. Upgrade setuptools and wheel:
   Ensure that your `setuptools` and `wheel` packages are up-to-date. You can upgrade them using the following commands:
   ```bash
   pip install --upgrade setuptools wheel
   ```

2. Install Visual Studio Build Tools:
   The errors seem to be related to the Microsoft Visual Studio compiler. Make sure you have the necessary build tools installed. You can download the Visual Studio Build Tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/).

3. Check Python Version:
   Ensure you are using a compatible Python version. Some packages have specific compatibility requirements. You can check the package documentation for any version-specific information.

4. Check `hoedown` Compatibility:
   Check if the version of `hoedown` you are trying to install is compatible with your Python version and the build tools you have installed. You may find this information in the package documentation or on the package's PyPI page.

5. Try an Alternative Markdown Library:
   If the issue persists, consider using an alternative markdown library that may have better compatibility with your environment. Popular alternatives include `markdown` and `mistune`.

   ```bash
   pip install markdown
   ```

   or

   ```bash
   pip install mistune
   ```

6. Contact Package Maintainers:
   If the problem persists, consider reaching out to the maintainers of the `hoedown` package for support. They may be aware of compatibility issues and might provide guidance or updates.

Remember to activate your virtual environment (`vlogger`) before attempting to install or upgrade packages.

**Comment by waternight1029** [comment]
pip install mistune——Thank you! It works for me!

But I met another problem.

model ready!
protagonists ready!
Traceback (most recent call last):
  File "C:\Users\xxx\Documents\Vlogger\sample_scripts\vlog_read_script_sample.py", line 303, in <module>
    main(omega_conf)
  File "C:\Users\xxx\Documents\Vlogger\sample_scripts\vlog_read_script_sample.py", line 157, in main
    video_list = readscript(args.script_file_path)
  File "C:\Users\xxx\Documents\Vlogger\vlogger\planning_utils\gpt4_utils.py", line 530, in readscript
    video_fragments = ast.literal_eval(script)
  File "C:\Users\xxx\anaconda3\envs\vlogger\lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "C:\Users\xxx\anaconda3\envs\vlogger\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
ValueError: source code string cannot contain null bytes

**Comment by zhuangshaobin** [comment]
I'm glad to see that your environmental issues have been resolved.

Based on the current error information you provided, potential issues can be categorized into two scenarios:

1. If you did not use the default configs/vlog_read_script_sample.yaml as the configuration file for sample_scripts/vlog_read_script_sample.py and instead modified the script file, you need to compare it with the scripts in the repository I provided. Check if there are any differences in formatting, as content generated by GPT may occasionally deviate from the interface I designed.

2. If you used the default configs/vlog_read_script_sample.yaml as the configuration file, it's possible that you accidentally modified some scripts within it. In this case, you can directly download and replace the original files with the script files I provided.

**Comment by waternight1029** [comment]
> I'm glad to see that your environmental issues have been resolved.
> 
> Based on the current error information you provided, potential issues can be categorized into two scenarios:
> 
> 1. If you did not use the default configs/vlog_read_script_sample.yaml as the configuration file for sample_scripts/vlog_read_script_sample.py and instead modified the script file, you need to compare it with the scripts in the repository I provided. Check if there are any differences in formatting, as content generated by GPT may occasionally deviate from the interface I designed.
> 2. If you used the default configs/vlog_read_script_sample.yaml as the configuration file, it's possible that you accidentally modified some scripts within it. In this case, you can directly download and replace the original files with the script files I provided.

Thank you so much, I did it!
