### ISSUE TITLE
error when python vlog_read_script_sample.py script

### ISSUE THREAD

**Issue by shanghailiwei** [Vchitect/Vlogger#9]
vlogger_backup) root@ubuntu-vm01:/sdb/github/Vlogger# python sample_scripts/vlog_read_script_sample.py 
/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/sdb/github/Vlogger
Seed set to 3407
pretrained/stable-diffusion-v1-4/unet/config.json
Traceback (most recent call last):
  File "/sdb/github/Vlogger/sample_scripts/vlog_read_script_sample.py", line 304, in <module>
    main(omega_conf)
  File "/sdb/github/Vlogger/sample_scripts/vlog_read_script_sample.py", line 119, in main
    model = get_models(args).to(device)
  File "/sdb/github/Vlogger/models/__init__.py", line 30, in get_models
    return UNet3DConditionModel.from_pretrained_2d(pretrained_model_path, subfolder="unet", use_concat=args.use_mask)
  File "/sdb/github/Vlogger/models/unet.py", line 654, in from_pretrained_2d
    state_dict = torch.load(model_file, map_location="cpu")
  File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by zhuangshaobin** [comment]
Here are some steps to troubleshoot this error:

· Verify that the file you are trying to load (model_file) exists and is complete.

· Ensure that the file is indeed a pickle file and that it has not been accidentally modified or corrupted.

· If you have access to the original file or a backup, try replacing the possibly corrupted file with a known good version.

· If this file is downloaded from the internet, make sure the download was successful and the file is not partially downloaded.

**Comment by shanghailiwei** [comment]
thanks for your reply and guiding,I just downloaded and pass to the next step. 


Traceback (most recent call last):
  File "/sdb/github/Vlogger/vlog_read_script_sample.py", line 306, in <module>
    main(omega_conf)
  File "/sdb/github/Vlogger/vlog_read_script_sample.py", line 160, in main
    video_list = readscript(args.script_file_path)
  File "/sdb/github/Vlogger/vlogger/planning_utils/gpt4_utils.py", line 531, in readscript
    video_fragments = ast.literal_eval(script)
  File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
ValueError: source code string cannot contain null bytes

**Comment by shanghailiwei** [comment]
Claude3 tell me to add teh sub sentence, solve the problem. 
        reference_file = f.read()
        reference_file = re.sub(r'\x00', '', reference_file)  # Remove null bytes

**Comment by zhuangshaobin** [comment]
> Claude3 tell me to add teh sub sentence, solve the problem. reference_file = f.read() reference_file = re.sub(r'\x00', '', reference_file) # Remove null bytes

I appreciate Claude3's answer and thank you for your attention to our project~!

**Comment by shanghailiwei** [comment]
(vlogger_backup) root@ubuntu-vm01:/sdb/github/Vlogger# python sample_scripts/vlog_read_script_sample.py 
Seed set to 3407
pretrained/stable-diffusion-v1-4/unet/config.json
Warnning: using half percision for inferencing!
model ready!

protagonists ready!
video script ready!
reference script ready!
zh script ready!
time script ready!
Generating the (Teddy bear in a kid's room.) prompt，  keep this status long time.  GPU memory consume 18.52G, bug GPU 0%, what can I do for the next step.

**Comment by YanzhaoDrew** [comment]
> thanks for your reply and guiding,I just downloaded and pass to the next step.
> 
> Traceback (most recent call last): File "/sdb/github/Vlogger/vlog_read_script_sample.py", line 306, in main(omega_conf) File "/sdb/github/Vlogger/vlog_read_script_sample.py", line 160, in main video_list = readscript(args.script_file_path) File "/sdb/github/Vlogger/vlogger/planning_utils/gpt4_utils.py", line 531, in readscript video_fragments = ast.literal_eval(script) File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/ast.py", line 64, in literal_eval node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval') File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/ast.py", line 50, in parse return compile(source, filename, mode, flags, ValueError: source code string cannot contain null bytes

I found that error reason is that the files from `results/vlog/teddy_travel/script/protagonist_place_reference.txt` and `results/vlog/teddy_travel/script/video_prompts.txt`contain Garbled characters. We need to replace those characters with corresponding scripts. It would be better that the author recorrects those files.  
![图片](https://github.com/Vchitect/Vlogger/assets/113875830/3cab764c-b7a9-47d1-aecc-14e31eabbf2d)

**Comment by zhuangshaobin** [comment]
> > thanks for your reply and guiding,I just downloaded and pass to the next step.
> > Traceback (most recent call last): File "/sdb/github/Vlogger/vlog_read_script_sample.py", line 306, in main(omega_conf) File "/sdb/github/Vlogger/vlog_read_script_sample.py", line 160, in main video_list = readscript(args.script_file_path) File "/sdb/github/Vlogger/vlogger/planning_utils/gpt4_utils.py", line 531, in readscript video_fragments = ast.literal_eval(script) File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/ast.py", line 64, in literal_eval node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval') File "/sdb/anaconda3/envs/vlogger_backup/lib/python3.10/ast.py", line 50, in parse return compile(source, filename, mode, flags, ValueError: source code string cannot contain null bytes
> 
> I found that error reason is that the files from `results/vlog/teddy_travel/script/protagonist_place_reference.txt` and `results/vlog/teddy_travel/script/video_prompts.txt`contain Garbled characters. We need to replace those characters with corresponding scripts. It would be better that the author recorrects those files. ![图片](https://private-user-images.githubusercontent.com/113875830/313989291-3cab764c-b7a9-47d1-aecc-14e31eabbf2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDkwMTMsIm5iZiI6MTcxMDg0ODcxMywicGF0aCI6Ii8xMTM4NzU4MzAvMzEzOTg5MjkxLTNjYWI3NjRjLWI3YTktNDdkMS1hZWNjLTE0ZTMxZWFiYmYyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMTQ1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWQ0N2U5YjM0NmNiMmQ3NzcwODU4MDg0ZjM2MzQ0Zjk4NjYyNTYxYzRiODMyZWUwZjUxOTMxZGFjYjQ5NTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yj8PIoo6I26rWfhxia8kWZlQ-pGjzyYXcG7IDgHR8Dc)


Thanks, this is indeed an oversight on my part and I will resolve this issue as soon as possible after checking.
